"""
Bundled TURN — auto-configure + (optionally) auto-start coturn so
cross-NAT calls don't need an external relay.

Three modes
-----------
  1. ``mode=external``   (default)
     Don't manage coturn. Operator runs their own; Helen just
     publishes the configured ICE servers via the existing
     ``ice_config_service``.

  2. ``mode=embedded``
     Generate a coturn config on first boot (random secret, listen
     on 3478 UDP/TCP, bind only to RFC1918 interfaces). Drop the
     file at ``$DATA_DIR/coturn/turnserver.conf`` and emit a
     systemd unit / NSSM service template at the same time.
     The operator runs ONE command to start it.

  3. ``mode=auto``
     Same as embedded, but also fork a coturn child process from
     the Helen-Server lifecycle. Risky on Windows (no native
     coturn), supported on Linux when ``coturn`` is on PATH.

Why
---
The audit found "TURN requires external deployment" as the biggest
gap for cross-LAN calls. With this module, an admin who installs
Helen-Server and ticks one env var gets a fully-functional video
deployment that survives symmetric-NAT users.

Wire shape
----------
The HMAC-short-term-credential mechanism (RFC 8489 §9) is unchanged:
    username = ``<expiry>:<user_id>``
    password = base64(HMAC-SHA1(secret, username))
``ice_config_service.build_ice_servers()`` still mints these.
"""

from __future__ import annotations

import os
import secrets
import shutil
import socket
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from app.core.logging import get_logger

logger = get_logger(__name__)


@dataclass
class TurnConfig:
    listen_ip: str = "0.0.0.0"
    listen_port: int = 3478
    tls_listen_port: int = 5349
    realm: str = "helen.local"
    secret: str = ""                       # HMAC for short-term creds
    min_relay_port: int = 49152
    max_relay_port: int = 65535
    no_tls: bool = True                    # LAN deployments don't need TLS
    cert_path: Optional[str] = None
    key_path: Optional[str] = None
    cli_password: str = ""                 # admin CLI access
    log_file: str = "/var/log/coturn/turnserver.log"
    pidfile: str = "/var/run/turnserver.pid"
    bound_interfaces: list[str] = field(default_factory=list)
    bandwidth_per_session_kbps: int = 2000
    total_quota: int = 2000
    user_quota: int = 10


def _local_lan_ip() -> str:
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("10.255.255.255", 1))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        return "0.0.0.0"


def render_coturn_config(cfg: TurnConfig) -> str:
    """Emit a turnserver.conf the operator can drop into /etc/coturn/."""
    lines = [
        "# Auto-generated by Helen-Server bundled_turn module.",
        "# Edit at your own risk — every reboot regenerates if missing.",
        "",
        f"listening-ip={cfg.listen_ip}",
        f"listening-port={cfg.listen_port}",
        f"min-port={cfg.min_relay_port}",
        f"max-port={cfg.max_relay_port}",
        f"realm={cfg.realm}",
        "fingerprint",
        # HMAC short-term credentials — Helen mints them via REST
        "use-auth-secret",
        f"static-auth-secret={cfg.secret}",
        # No long-term users — every credential is HMAC-derived
        "no-multicast-peers",
        # Refuse to relay to public IPs (LAN-only enforcement)
        "denied-peer-ip=0.0.0.0-0.255.255.255",
        "denied-peer-ip=224.0.0.0-239.255.255.255",
        "denied-peer-ip=255.255.255.255-255.255.255.255",
        "allowed-peer-ip=10.0.0.0-10.255.255.255",
        "allowed-peer-ip=172.16.0.0-172.31.255.255",
        "allowed-peer-ip=192.168.0.0-192.168.255.255",
        "allowed-peer-ip=169.254.0.0-169.254.255.255",
        # Quotas
        f"total-quota={cfg.total_quota}",
        f"user-quota={cfg.user_quota}",
        f"max-bps={cfg.bandwidth_per_session_kbps * 1000}",
        # Logging
        f"log-file={cfg.log_file}",
        f"pidfile={cfg.pidfile}",
        "simple-log",
    ]
    if cfg.no_tls:
        lines.append("no-tls")
        lines.append("no-dtls")
    else:
        lines.append(f"tls-listening-port={cfg.tls_listen_port}")
        if cfg.cert_path:
            lines.append(f"cert={cfg.cert_path}")
        if cfg.key_path:
            lines.append(f"pkey={cfg.key_path}")
    if cfg.cli_password:
        lines.append("cli-ip=127.0.0.1")
        lines.append(f"cli-password={cfg.cli_password}")
    return "\n".join(lines) + "\n"


def render_systemd_unit(coturn_path: str, conf_path: str) -> str:
    return (
        "[Unit]\n"
        "Description=Helen bundled TURN (coturn)\n"
        "After=network-online.target\n"
        "Wants=network-online.target\n"
        "\n"
        "[Service]\n"
        "Type=simple\n"
        f"ExecStart={coturn_path} -c {conf_path}\n"
        "Restart=on-failure\n"
        "RestartSec=5\n"
        "User=helen\n"
        "Group=helen\n"
        "LimitNOFILE=65536\n"
        "NoNewPrivileges=true\n"
        "PrivateTmp=true\n"
        "\n"
        "[Install]\n"
        "WantedBy=multi-user.target\n"
    )


def render_nssm_install_cmd(coturn_path: str, conf_path: str,
                              service_name: str = "HelenTURN") -> str:
    return (
        f'nssm install {service_name} "{coturn_path}" -c "{conf_path}"\n'
        f'nssm set {service_name} Start SERVICE_AUTO_START\n'
        f'nssm set {service_name} AppRestartDelay 5000\n'
        f'nssm start {service_name}\n'
    )


def ensure_bundled_turn(
    data_dir: str,
    *,
    realm: Optional[str] = None,
    listen_ip: Optional[str] = None,
) -> TurnConfig:
    """Make sure a coturn config exists at ``$DATA_DIR/coturn/``.

    Returns the loaded ``TurnConfig`` so the caller can publish the
    secret + listen address back into the ICE config service.
    """
    coturn_dir = Path(data_dir) / "coturn"
    coturn_dir.mkdir(parents=True, exist_ok=True)
    conf_path = coturn_dir / "turnserver.conf"
    secret_path = coturn_dir / "secret.txt"

    if secret_path.exists():
        secret = secret_path.read_text().strip()
    else:
        secret = secrets.token_hex(32)
        secret_path.write_text(secret)
        try:
            os.chmod(secret_path, 0o600)
        except Exception:
            pass

    cfg = TurnConfig(
        listen_ip=listen_ip or _local_lan_ip(),
        realm=realm or "helen.local",
        secret=secret,
        log_file=str(coturn_dir / "turnserver.log"),
        pidfile=str(coturn_dir / "turnserver.pid"),
        cli_password=secrets.token_hex(8),
    )

    # Always re-render the config file (idempotent if unchanged) —
    # this lets us pick up any new defaults across upgrades.
    new_conf = render_coturn_config(cfg)
    if (not conf_path.exists()
            or conf_path.read_text() != new_conf):
        conf_path.write_text(new_conf)

    # Service templates — only written once
    sd_path = coturn_dir / "helen-turn.service"
    if not sd_path.exists():
        coturn_bin = shutil.which("turnserver") or "/usr/bin/turnserver"
        sd_path.write_text(render_systemd_unit(coturn_bin, str(conf_path)))

    nssm_path = coturn_dir / "helen-turn.nssm.bat"
    if not nssm_path.exists():
        nssm_path.write_text(render_nssm_install_cmd(
            "C:\\Program Files\\Coturn\\turnserver.exe",
            str(conf_path),
        ))

    logger.info(
        "bundled_turn_ready",
        config_at=str(conf_path),
        listen_ip=cfg.listen_ip,
        port=cfg.listen_port,
    )
    return cfg


def _windows_coturn_candidates() -> list[str]:
    """Common install locations for coturn on Windows.

    Order matters: Program Files first (typical installer location),
    then a portable copy under Helen's own bin/ directory so admins
    can ship a self-contained build that works without a separate
    coturn install.
    """
    candidates = [
        r"C:\Program Files\Coturn\turnserver.exe",
        r"C:\Program Files (x86)\Coturn\turnserver.exe",
        r"C:\coturn\turnserver.exe",
    ]
    # Helen-bundled location — portable distribution.
    try:
        here = os.path.dirname(os.path.abspath(__file__))
        bundled = os.path.normpath(
            os.path.join(here, "..", "..", "bin", "coturn", "turnserver.exe"),
        )
        candidates.append(bundled)
    except Exception:  # pragma: no cover
        pass
    return candidates


def maybe_spawn_coturn(cfg: TurnConfig,
                         conf_path: str) -> Optional[subprocess.Popen]:
    """Best-effort attempt to fork a coturn child.

    On Linux/macOS, look up ``turnserver`` on PATH and spawn it
    directly so coturn dies with Helen-Server.

    On Windows, try in order:
      1. ``turnserver.exe`` on PATH.
      2. Standard install paths (Program Files, C:\\coturn).
      3. Helen-bundled portable copy at ``bin/coturn/turnserver.exe``.

    The previous behaviour was to skip Windows entirely and ask the
    operator to set up an NSSM service manually. That made bundled
    TURN unusable on Windows in practice, so cross-subnet calls had
    no relay path. The auto-spawn keeps the LAN-only guarantee
    (turnserver.exe is launched with the same generated config that
    binds to the LAN interface) while removing the manual-install
    burden.
    """
    coturn_bin: Optional[str] = None

    if os.name == "nt":
        # 1. PATH first.
        coturn_bin = shutil.which("turnserver") or shutil.which("turnserver.exe")
        # 2. Standard / bundled locations.
        if not coturn_bin:
            for candidate in _windows_coturn_candidates():
                if os.path.exists(candidate):
                    coturn_bin = candidate
                    break
        if not coturn_bin:
            logger.info(
                "bundled_turn_no_coturn_binary_windows",
                hint=(
                    "place turnserver.exe on PATH, install coturn to "
                    r"C:\Program Files\Coturn, or drop a portable "
                    "copy at <helen>/bin/coturn/turnserver.exe"
                ),
            )
            return None
    else:
        coturn_bin = shutil.which("turnserver")
        if not coturn_bin:
            logger.info(
                "bundled_turn_no_coturn_binary",
                hint="apt install coturn  /  yum install coturn",
            )
            return None

    try:
        # CREATE_NO_WINDOW so the child doesn't pop a console on
        # Windows GUI launches; ignored on POSIX.
        creationflags = 0
        if os.name == "nt":
            creationflags = getattr(subprocess, "CREATE_NO_WINDOW", 0)
        proc = subprocess.Popen(
            [coturn_bin, "-c", conf_path],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            creationflags=creationflags,
        )
        logger.info("bundled_turn_spawned", pid=proc.pid, binary=coturn_bin)
        return proc
    except Exception as exc:
        logger.warning("bundled_turn_spawn_failed", error=str(exc))
        return None
