include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - "lib/l10n/generated/**"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_annotation_target: ignore
    todo: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - prefer_final_in_for_each
    - avoid_print
    - avoid_returning_null_for_future
    - always_declare_return_types
    - require_trailing_commas
    - sort_pub_dependencies
    - unawaited_futures
    - use_super_parameters
    - prefer_single_quotes
    - directives_ordering
    - prefer_relative_imports
    - sized_box_for_whitespace
