{{- if and .Values.server.enabled .Values.server.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "helen.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helen.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.server.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "helen.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
{{- end }}
