{{- if .Values.auth.autoCreateJwtSecret }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace .Values.auth.jwtSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.jwtSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helen.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $existing }}
  {{ .Values.auth.jwtSecretKey }}: {{ index $existing.data .Values.auth.jwtSecretKey }}
  {{- else }}
  {{ .Values.auth.jwtSecretKey }}: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if .Values.postgres.enabled }}
---
{{- $existing := lookup "v1" "Secret" .Release.Namespace .Values.postgres.passwordSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.passwordSecretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if $existing }}
  {{ .Values.postgres.passwordSecretKey }}: {{ index $existing.data .Values.postgres.passwordSecretKey }}
  {{- else }}
  {{ .Values.postgres.passwordSecretKey }}: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if .Values.redis.enabled }}
---
{{- $existing := lookup "v1" "Secret" .Release.Namespace .Values.redis.passwordSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.passwordSecretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if $existing }}
  {{ .Values.redis.passwordSecretKey }}: {{ index $existing.data .Values.redis.passwordSecretKey }}
  {{- else }}
  {{ .Values.redis.passwordSecretKey }}: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if .Values.rendezvous.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helen.rendezvous.fullname" . }}-token
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  token: {{ default (randAlphaNum 48) .Values.rendezvous.env.HELEN_RENDEZVOUS_TOKEN | b64enc | quote }}
{{- end }}
