{{- if and .Values.server.enabled .Values.server.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helen.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helen.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.server.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.server.ingress.className }}
  ingressClassName: {{ .Values.server.ingress.className }}
  {{- end }}
  {{- if .Values.server.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.server.ingress.hostname }}
      secretName: {{ .Values.server.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.server.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "helen.server.fullname" . }}
                port:
                  number: {{ .Values.server.service.port }}
{{- end }}
