"""
Module L — Helen Agent models.

Tables
------
agents          — one row per device that has paired with the server
agent_events    — append-only log of state transitions and command output
agent_commands  — queued / executed commands targeting an agent

A device is uniquely identified by its `fingerprint` (SHA-256 of stable
hardware anchors generated by the Rust agent).  The refresh-token hash
stored here is rotated whenever an admin revokes a session via
`POST /api/agents/{id}/rotate-token`.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, UUIDPrimaryKeyMixin, utc_now


# ─────────────────────────────────────────────────────────────────────────────
# Agent
# ─────────────────────────────────────────────────────────────────────────────


class Agent(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = "agents"
    __table_args__ = (
        UniqueConstraint("fingerprint", name="uq_agents_fingerprint"),
        Index("ix_agents_status_last_heartbeat", "status", "last_heartbeat_at"),
    )

    fingerprint: Mapped[str] = mapped_column(
        String(64), nullable=False, index=True,
    )
    hostname: Mapped[str] = mapped_column(String(256), nullable=False, default="unknown")
    os_name: Mapped[str | None] = mapped_column(String(64), nullable=True)
    os_version: Mapped[str | None] = mapped_column(String(128), nullable=True)
    agent_version: Mapped[str | None] = mapped_column(String(32), nullable=True)

    registered_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utc_now, nullable=False,
    )
    last_heartbeat_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, index=True,
    )

    # "online" | "offline" | "stale" | "revoked"
    status: Mapped[str] = mapped_column(
        String(16), nullable=False, default="offline", index=True,
    )

    # Optional workspace/tenant binding — nullable until Module H lands.
    workspace_id: Mapped[str | None] = mapped_column(String(32), nullable=True, index=True)

    # SHA-256 of the long-lived refresh token. Never store the token itself.
    refresh_token_hash: Mapped[str | None] = mapped_column(String(128), nullable=True)
    refresh_token_issued_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    refresh_token_version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)

    # Optional public key for future signed-event verification.
    public_key: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Latest snapshot JSON (deduplicated — only stored once per heartbeat).
    last_snapshot_json: Mapped[str | None] = mapped_column(Text, nullable=True)

    # IP of the most recent control connection.
    last_ip: Mapped[str | None] = mapped_column(String(64), nullable=True)

    # Soft-delete flag.
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    # Relationships
    events: Mapped[list["AgentEvent"]] = relationship(
        "AgentEvent",
        back_populates="agent",
        cascade="all, delete-orphan",
        lazy="selectin",
    )
    commands: Mapped[list["AgentCommand"]] = relationship(
        "AgentCommand",
        back_populates="agent",
        cascade="all, delete-orphan",
        lazy="selectin",
    )

    def __repr__(self) -> str:
        return f"<Agent {self.id[:8]} host={self.hostname} status={self.status}>"


# ─────────────────────────────────────────────────────────────────────────────
# AgentEvent
# ─────────────────────────────────────────────────────────────────────────────


class AgentEvent(Base, UUIDPrimaryKeyMixin):
    __tablename__ = "agent_events"
    __table_args__ = (
        Index("ix_agent_events_agent_created", "agent_id", "created_at"),
        Index("ix_agent_events_type", "event_type"),
    )

    agent_id: Mapped[str] = mapped_column(
        String(32),
        ForeignKey("agents.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # "registered" | "heartbeat" | "command_started" | "command_finished"
    # | "command_failed" | "file_uploaded" | "file_downloaded"
    # | "screen_captured" | "updated" | "revoked" | "stale" | "online" | "offline"
    event_type: Mapped[str] = mapped_column(String(48), nullable=False)
    payload_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utc_now, nullable=False,
    )

    agent: Mapped["Agent"] = relationship("Agent", back_populates="events")

    def __repr__(self) -> str:
        return f"<AgentEvent {self.event_type} agent={self.agent_id[:8]}>"


# ─────────────────────────────────────────────────────────────────────────────
# AgentCommand
# ─────────────────────────────────────────────────────────────────────────────


class AgentCommand(Base, UUIDPrimaryKeyMixin):
    __tablename__ = "agent_commands"
    __table_args__ = (
        Index("ix_agent_commands_agent_status", "agent_id", "status"),
        Index("ix_agent_commands_issued_at", "issued_at"),
    )

    agent_id: Mapped[str] = mapped_column(
        String(32),
        ForeignKey("agents.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    command: Mapped[str] = mapped_column(String(128), nullable=False)
    args_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    # "queued" | "dispatched" | "running" | "completed" | "failed" | "timeout"
    status: Mapped[str] = mapped_column(
        String(16), nullable=False, default="queued", index=True,
    )
    stdout: Mapped[str | None] = mapped_column(Text, nullable=True)
    stderr: Mapped[str | None] = mapped_column(Text, nullable=True)
    exit_code: Mapped[int | None] = mapped_column(Integer, nullable=True)
    duration_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)

    issued_by: Mapped[str] = mapped_column(String(32), nullable=False, default="system")
    issued_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utc_now, nullable=False,
    )
    dispatched_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )

    timeout_secs: Mapped[int] = mapped_column(Integer, nullable=False, default=30)

    agent: Mapped["Agent"] = relationship("Agent", back_populates="commands")

    def __repr__(self) -> str:
        return f"<AgentCommand {self.id[:8]} {self.command} status={self.status}>"
