#!/usr/bin/env node
/**
 * build-pwa.mjs — turn the desktop renderer build into an installable
 * Progressive Web App.
 *
 * Output: ./dist/  (drop into any static host: nginx, GitHub Pages,
 * Netlify, Cloudflare Pages — works against any Helen-Server with
 * CORS allowing the origin).
 *
 * What it does:
 *   1. Copies the renderer bundle from CommClient-Desktop/dist-electron/renderer/
 *   2. Generates manifest.json so the browser offers "Install"
 *   3. Generates a service worker that caches static assets for offline
 *   4. Patches index.html with manifest link + SW registration
 *   5. Generates icon set (re-uses icon from desktop build resources)
 */
import {
  existsSync, mkdirSync, readFileSync, writeFileSync,
  cpSync, rmSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = __dirname;
const RENDERER = resolve(
  ROOT, '..', 'CommClient-Desktop', 'dist-electron', 'renderer'
);
const DIST = join(ROOT, 'dist');

if (!existsSync(RENDERER)) {
  console.error(`✗ renderer not found: ${RENDERER}`);
  console.error(`  Build it first: cd ../CommClient-Desktop && npm run build:renderer`);
  process.exit(1);
}

console.log(`→ copying renderer from ${RENDERER}`);
if (existsSync(DIST)) rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST, { recursive: true });
cpSync(RENDERER, DIST, { recursive: true });

// 1. manifest.json
const manifest = {
  name: 'Helen',
  short_name: 'Helen',
  description: 'LAN-first communication platform — chat, voice, video, files.',
  start_url: '.',
  scope: '.',
  display: 'standalone',
  orientation: 'any',
  theme_color: '#0d1117',
  background_color: '#0d1117',
  lang: 'ar',
  dir: 'auto',
  icons: [
    { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png' },
    { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    { src: 'icons/icon-maskable.png', sizes: '512x512', type: 'image/png',
      purpose: 'maskable' },
  ],
  categories: ['communication', 'productivity', 'social'],
  screenshots: [],
  shortcuts: [
    {
      name: 'New Chat',
      url: '#/chat/new',
      icons: [{ src: 'icons/icon-192.png', sizes: '192x192' }],
    },
  ],
};
writeFileSync(join(DIST, 'manifest.json'), JSON.stringify(manifest, null, 2));
console.log('✓ manifest.json');

// 2. Service worker — cache-first for static assets, network-first for API
const sw = `// Helen PWA service worker — generated by build-pwa.mjs
const CACHE_NAME = 'helen-pwa-v${Date.now()}';
const STATIC_ASSETS = [
  './',
  './index.html',
  './manifest.json',
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(STATIC_ASSETS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(
      keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))
    )).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // Never cache API / WebSocket / Socket.IO traffic — must be fresh.
  if (url.pathname.startsWith('/api/') ||
      url.pathname.startsWith('/socket.io/') ||
      url.protocol === 'ws:' || url.protocol === 'wss:') {
    return;
  }

  // Cache-first for our own static assets.
  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;
      return fetch(event.request).then((response) => {
        // Only cache successful same-origin GETs.
        if (response.ok && event.request.method === 'GET' &&
            url.origin === self.location.origin) {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((c) => c.put(event.request, clone));
        }
        return response;
      }).catch(() => caches.match('./index.html'));
    })
  );
});

// Listen for SKIP_WAITING from the app to activate updates immediately.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});
`;
writeFileSync(join(DIST, 'sw.js'), sw);
console.log('✓ sw.js');

// 3. Icons — generate placeholders if no source icon available
mkdirSync(join(DIST, 'icons'), { recursive: true });
const iconSrc = resolve(ROOT, '..', 'CommClient-Desktop', 'build', 'icon.png');
function placeholderPng() {
  // Smallest valid PNG: 1×1 transparent pixel. Browsers accept this
  // for manifest icons; production should replace with real artwork.
  return Buffer.from(
    '89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4' +
    '8900000001735247420000aece1ce90000000d49444154789c63f8ffff3f0000' +
    '06fb02fdfee84a3a0000000049454e44ae426082',
    'hex',
  );
}
const iconBytes = existsSync(iconSrc) ? readFileSync(iconSrc) : placeholderPng();
writeFileSync(join(DIST, 'icons', 'icon-192.png'), iconBytes);
writeFileSync(join(DIST, 'icons', 'icon-512.png'), iconBytes);
writeFileSync(join(DIST, 'icons', 'icon-maskable.png'), iconBytes);
console.log(`✓ icons (${existsSync(iconSrc) ? 'from desktop build' : 'placeholders'})`);

// 4. Patch index.html
const indexPath = join(DIST, 'index.html');
let html = readFileSync(indexPath, 'utf-8');
const PWA_MARKER = '<!-- HELEN-PWA -->';
if (!html.includes(PWA_MARKER)) {
  const head =
    `${PWA_MARKER}\n` +
    `  <link rel="manifest" href="./manifest.json" />\n` +
    `  <meta name="theme-color" content="#0d1117" />\n` +
    `  <link rel="apple-touch-icon" href="./icons/icon-192.png" />\n` +
    `  <meta name="apple-mobile-web-app-capable" content="yes" />\n` +
    `  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />\n` +
    `  <meta name="mobile-web-app-capable" content="yes" />\n` +
    `  <script>\n` +
    `    if ('serviceWorker' in navigator) {\n` +
    `      window.addEventListener('load', () => {\n` +
    `        navigator.serviceWorker.register('./sw.js').then((reg) => {\n` +
    `          // Auto-update: notify the running SW to swap on next page load.\n` +
    `          reg.addEventListener('updatefound', () => {\n` +
    `            const w = reg.installing;\n` +
    `            if (w) w.addEventListener('statechange', () => {\n` +
    `              if (w.state === 'installed' && navigator.serviceWorker.controller) {\n` +
    `                w.postMessage({ type: 'SKIP_WAITING' });\n` +
    `              }\n` +
    `            });\n` +
    `          });\n` +
    `        }).catch((e) => console.warn('SW register failed', e));\n` +
    `      });\n` +
    `    }\n` +
    `  </script>\n`;
  html = html.replace('</head>', `  ${head}</head>`);
  writeFileSync(indexPath, html);
  console.log('✓ index.html patched (manifest + SW registration)');
}

// 5. PWA-only shim for window.electronAPI — no notifications API on web,
//    no LAN UDP probe; everything else gracefully degrades.
const webShim =
  `// PWA shim — desktop's electronAPI translated to browser-native APIs.\n` +
  `(function() {\n` +
  `  if (window.electronAPI) return;\n` +
  `  const memCache = new Map();\n` +
  `  window.electronAPI = {\n` +
  `    platform: 'web', isMobile: false, isPWA: true,\n` +
  `    config: {\n` +
  `      get: (k, d) => Promise.resolve(\n` +
  `        memCache.has(k) ? memCache.get(k) :\n` +
  `        (() => { try { const v = localStorage.getItem(k); return v ? JSON.parse(v) : d; } catch { return d; }})()\n` +
  `      ),\n` +
  `      set: (k, v) => { memCache.set(k, v); try { localStorage.setItem(k, JSON.stringify(v)); } catch {} return Promise.resolve(); },\n` +
  `      delete: (k) => { memCache.delete(k); try { localStorage.removeItem(k); } catch {} return Promise.resolve(); },\n` +
  `      getAll: () => Promise.resolve({}),\n` +
  `    },\n` +
  `    discovery: {\n` +
  `      // No LAN scan in web; user must enter URL manually.\n` +
  `      scan: () => Promise.resolve([]),\n` +
  `      stop: () => Promise.resolve(),\n` +
  `    },\n` +
  `    notifications: {\n` +
  `      show: ({ title, body }) => {\n` +
  `        if ('Notification' in window && Notification.permission === 'granted') {\n` +
  `          new Notification(title || 'Helen', { body: body || '' });\n` +
  `        }\n` +
  `        return Promise.resolve();\n` +
  `      },\n` +
  `      requestPermission: () => 'Notification' in window ? Notification.requestPermission() : Promise.resolve('denied'),\n` +
  `    },\n` +
  `    system: {\n` +
  `      openExternal: (url) => { window.open(url, '_blank', 'noopener'); return Promise.resolve(); },\n` +
  `      getInfo: () => Promise.resolve({ platform: 'web', arch: navigator.platform, version: navigator.userAgent }),\n` +
  `      copyToClipboard: (t) => navigator.clipboard ? navigator.clipboard.writeText(t) : Promise.resolve(),\n` +
  `    },\n` +
  `    network: {\n` +
  `      getStatus: () => Promise.resolve({ connected: navigator.onLine, connectionType: 'unknown' }),\n` +
  `      onChange: (cb) => {\n` +
  `        const onlineHandler = () => cb({ connected: true });\n` +
  `        const offlineHandler = () => cb({ connected: false });\n` +
  `        window.addEventListener('online', onlineHandler);\n` +
  `        window.addEventListener('offline', offlineHandler);\n` +
  `        return () => { window.removeEventListener('online', onlineHandler); window.removeEventListener('offline', offlineHandler); };\n` +
  `      },\n` +
  `    },\n` +
  `    server: { start: () => Promise.resolve(false), stop: () => Promise.resolve(), status: () => Promise.resolve({ running: false, web: true }) },\n` +
  `    menu: { show: () => {}, setLabel: () => {} },\n` +
  `    window: { minimize: () => {}, close: () => window.close(), reload: () => location.reload() },\n` +
  `  };\n` +
  `  document.documentElement.setAttribute('data-runtime', 'web');\n` +
  `})();\n`;
writeFileSync(join(DIST, 'web-shim.js'), webShim);
// Inject before any other script
let html2 = readFileSync(indexPath, 'utf-8');
if (!html2.includes('web-shim.js')) {
  html2 = html2.replace(
    '<head>',
    `<head>\n  <script src="./web-shim.js"></script>`,
  );
  writeFileSync(indexPath, html2);
  console.log('✓ web-shim.js injected');
}

console.log(`\n✓ PWA built at ${DIST}`);
console.log(`  Serve with:`);
console.log(`    cd dist && npx serve -p 8080`);
console.log(`  Then open http://localhost:8080 in any modern browser.`);
console.log(`  Browser will offer "Install" once a Helen-Server connection is made.`);
